import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'


export default function Home({newsResults, whoToFollowResults}) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed />
  
        {/* Widget Section */}
        <Widgets newsResults={newsResults.articles} 
          whoToFollowResults={whoToFollowResults.results}
        />
        {/* Modal */}
      </main>
      
    </div>
  )
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/in.json


export async function getServerSideProps(){
  const newsApiURL = "https://saurav.tech/NewsAPI/top-headlines/category/business/in.json";
  const newsResults = await fetch(newsApiURL).then((res) => res.json());
  
  // who to follow
  const whoToFollowURL="https://randomuser.me/api/?results=30&inc=name,login,picture";
  const whoToFollowResults = await fetch(whoToFollowURL).then((res) => res.json());

  return {
    props: {
      newsResults,
      whoToFollowResults,
    },
  };
}